runtime: java7
instance_class: F2
automatic_scaling:
  min_pending_latency: 30ms
  max_pending_latency: automatic
  min_idle_instances: 3
  max_idle_instances: automatic
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
api_version: '1.0'
handlers:
- url: (/.*\.nocache\..*\.cache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*\.cache\..*\.nocache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*\.cache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 365d
- url: (/.*\.nocache\..*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: .*\.jsp
  script: unused
  login: optional
  secure: optional
- url: /v1
  script: unused
  login: optional
  secure: optional
